# Generated by Django 4.2 on 2023-04-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Volcano',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Volcano_Name', models.CharField(max_length=255)),
                ('Volcano_Image', models.URLField(blank=True, null=True)),
                ('Volcano_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(max_length=255)),
                ('Region', models.CharField(blank=True, max_length=255, null=True)),
                ('Subregion', models.CharField(blank=True, max_length=255, null=True)),
                ('epoch_period', models.CharField(blank=True, max_length=255, null=True)),
                ('Summit_and_Elevation', models.CharField(blank=True, max_length=255, null=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_app.product')),
            ],
        ),
    ]
