# Generated by Django 4.2 on 2023-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volcano',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
